project_name: 'CoTIR-9B'

model:
  base_model_name: 'flux.2-klein-9b'
  cot_adapter:
    hidden_size: 4096
    num_heads: 32
    mlp_ratio: 4.0
    qk_scale: None
    out_channels: 12288
    depth: 6
  lora:
    enabled: true
    rank: 96
    scale: 1.0
    lora_bias: true
    merge_for_inference: false

inference:
  num_steps: 5
  base_model_path: /home/guoyu/guoyu_demo/ckpt/FLUX.2-klein-9B
  cot_adapter_path: ../ckpt/CoTIR-9B/cot_adapter.pt
  lora_path: ../ckpt/CoTIR-9B/lora.pt

mixed_precision: "bf16"
device: "cuda"

